# Site Settings
#theme: jekyll-theme-hacker
minimal_mistakes_skin : "default"
title: "My Data Science Journey"
name: "Michael Cheung"
description: "This website records my data science journey"

# Site Author
author:
  name: "Michael Cheung"
  bio:  "Associate Data Scientist at OOCL"
  location: "Hong Kong"
  github: "michaelcheung105"
  linkedin: "michaelcheung105"

# Defaults
defaults:
  #_posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time:  true
      share:  true
      related:  true

#  # _pages
#  - scope:
#      path: ""
#      type: pages
#    values:
#      layout: single
#      author_profile: true
